### ISSUE TITLE
getENSDFdata.py issue

### ISSUE THREAD

**Issue by xmatter** [shawest/neucbot#1]
The program would crash while trying to get the alpha data (see error below)

Line 36 of the getENSDFdata.py had Po-218 half life ((3.098%20m)) hard wired into the url.  I removed it and it seemed to fix the issue at least for some of the needed files.

generateALphaList( Bi 210 )
http://www.nndc.bnl.gov/chart/getdecaydataset.jsp?nucleus=206TL&dsid=210bi%20a%20decay%20(3.098%20m)
http://www.nndc.bnl.gov/ensdf/EnsdfDispatcherServlet?dbclass=ensdf&dataset_table=dataset_table&pagesource=singular&chooseit=View%20in%20ENSDF%20format&datasetcheck=206081001
ERROR: TIMEOUT
http://www.nndc.bnl.gov/ensdf/EnsdfDispatcherServlet?dbclass=ensdf&dataset_table=dataset_table&pagesource=singular&chooseit=View%20in%20ENSDF%20format&datasetcheck=206081001
Traceback (most recent call last):
  File "./neucbot.py", line 515, in <module>
    main()
  File "./neucbot.py", line 461, in main
    alpha_list = loadChainAlphaList(chain_file)
  File "./neucbot.py", line 99, in loadChainAlphaList
    aList_forIso = getAlphaListIfExists(ele,A)
  File "./neucbot.py", line 82, in getAlphaListIfExists
    generateAlphaList(ele,A)
  File "./neucbot.py", line 53, in generateAlphaList
    ensdf.main(['parseENSDF',ele,A])
  File "./Scripts/parseENSDF.py", line 135, in main
    getENSDFdata.main(argv)
  File "./Scripts/getENSDFdata.py", line 87, in main
    getPage(url, ele, A)
  File "./Scripts/getENSDFdata.py", line 16, in getPage
    page = urllib2.urlopen(req,timeout=3)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

**Comment by shawest** [comment]
Hi xmatter,
Thanks for the bug report! It looks like NNDC changed the URLs at which they store many of their ENSDF files, which breaks the part of my code that downloads them. The change includes the lifetime of the isotope in the URL, so it doesn't seem to be an easy fix. I'll work on getting this back up and running as soon as I can, but it may take a couple of days.

In the meantime, you can access the files from http://www.nndc.bnl.gov/chart/chartNuc.jsp by entering the isotope you're interested in on the right side of the screen. If you then select "decay radiation" at the bottom of the page, you can click "ENSDF file" next to the alpha decay. If you save this file in your NeuCBOT directory under Data/Decays/ensdfRn218.dat (for Rn218, for example), you should be able to run the code.

Hopefully I'll get this step automated again soon so you don't need to download the ENSDF files by hand.

**Comment by shawest** [comment]
Hi xmatter,
I sorted things out so NeuCBOT now finds the NNDC page on the isotope, retrieves a list of ENSDF links, and finds the one with the appropriate data. This should be fixed now, so I'm going to close the issue. Feel free to re-open it or open a new one if you encounter more problems!
